# This file contains values from Cookiecutter

default_context:
  project_name: "GenerativeZoo"
  repo_name: "GenerativeZoo"
  description: "Model Zoo for Generative Models"
  organization: "TU/e"
  license: "CC-BY-4.0"
  organization_email: "f.t.de.espirito.santo.e.caetano@tue.nl"
  line_length: "120"
  python_minimal_version: "3.9"
